// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tlqnjucajkinajjvskuk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRscW5qdWNhamtpbmFqanZza3VrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NTY2MTUsImV4cCI6MjA2MDIzMjYxNX0.EeQzGpfSMn9caH0fbnVbEHuhgw72NHa-r5yMamagc0c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);